# Generated by Django 5.1.1 on 2024-10-13 23:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HabitLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150, unique=True, verbose_name='Место положение')),
            ],
            options={
                'verbose_name': 'Место положение',
                'verbose_name_plural': 'Места положения',
            },
        ),
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
                ('action', models.CharField(max_length=300, verbose_name='Действие')),
                ('periodicity', models.PositiveIntegerField(default=1, verbose_name='Переодичность')),
                ('reward', models.CharField(blank=True, max_length=300, null=True, verbose_name='Вознаграждение')),
                ('duration', models.PositiveIntegerField(verbose_name='Время на выполнение')),
                ('day', models.DateField(default=datetime.date.today, verbose_name='День выполнения')),
                ('is_pleasant', models.BooleanField(verbose_name='Приятная привычка')),
                ('is_publicity', models.BooleanField(default=False, verbose_name='Опубликованна')),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='habits.habitlocation', verbose_name='Место положение')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
